<a href="https://colab.research.google.com/github/Saurabh-jha99/Credit-Card-Fraud-Detection-using-Maching-Learning/blob/main/Copy_of_Credit_Card_Fraud_Detection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credit card fraud is increasing considerably with the development of modern technology and the global superhighways of communication. Credit card fraud costs consumers and the financial company billions of dollars anually, and fraudsters continuosly try to find new rules and tactics to commit illegal actions. Thus , fraud detection systems have become essential for banks and financial institution, to minimize their losses. 

In [ ]:
# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Import the Dependencies


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Upload the Credit Card Dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving creditcard.csv to creditcard (2).csv


## Let's print first five row of data frame

In [ ]:
import io
data = pd.read_csv(io.BytesIO(uploaded['creditcard.csv']))


data.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

# Let's print last five row of data frame

In [ ]:
data.tail()

Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

# Now see information of dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

# Let's see if there is any missing value in each column

In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

# There is no missing value, so let's see the distribution of legit transaction and fraudlent transaction.

In [ ]:
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

# Seperating the data for Analysis

In [ ]:
legit=data[data.Class==0]
Fraudlent=data[data.Class==1]

# Print the shape of these variables

In [ ]:
print(legit.shape)
print(Fraudlent.shape)

(284315, 31)
(492, 31)


# Have a look at the statistical measurement of the data

In [ ]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
Fraudlent.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

# Compare the values for both transaction

In [ ]:
data.groupby('Class').mean()

Time        V1        V2  ...       V27       V28      Amount
Class                                    ...                                
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

# Handling the dataset

In [ ]:
legit_sample=legit.sample(n=492)

# Concatenating two data frames

In [ ]:
new_data=pd.concat([legit_sample,Fraudlent],axis=0)

In [ ]:
new_data.head()

Time        V1        V2  ...       V28  Amount  Class
33682    37337.0 -2.384763 -1.628066  ... -0.234126  163.42      0
196374  131476.0 -1.508364  2.101169  ...  0.062974    0.77      0
22524    32290.0  1.383417 -0.589567  ...  0.013516   15.00      0
240258  150515.0  1.336445 -1.206533  ...  0.010175  320.00      0
90552    63067.0  1.212394  0.268213  ... -0.009630    1.79      0

[5 rows x 31 columns]

In [ ]:
new_data.tail()

Time        V1        V2  ...       V28  Amount  Class
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[5 rows x 31 columns]

# Let's see the value count now

In [ ]:
new_data['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

# Look at the mean value

In [ ]:
new_data.groupby('Class').mean()

Time        V1        V2  ...       V27       V28      Amount
Class                                    ...                                
0      94010.804878 -0.073916  0.044035  ...  0.005754  0.005138   89.508841
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

# Now the dataset is ready to use. We will split the data into features and target

In [ ]:
X=new_data.drop(columns='Class',axis=1)
Y=new_data['Class']
print(X)
print(Y)

            Time        V1        V2  ...       V27       V28  Amount
33682    37337.0 -2.384763 -1.628066  ... -0.142034 -0.234126  163.42
196374  131476.0 -1.508364  2.101169  ...  0.724746  0.062974    0.77
22524    32290.0  1.383417 -0.589567  ...  0.010726  0.013516   15.00
240258  150515.0  1.336445 -1.206533  ... -0.008399  0.010175  320.00
90552    63067.0  1.212394  0.268213  ... -0.007007 -0.009630    1.79
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[984 rows x 30 columns]
33682     0
196374    0
22524     0
240258    0
90552     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Nam

# Split the data into Train set and Test set

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)


**Logistic** **Regression** **Model**

In [ ]:
classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Model Evaluation

Accuracy on training data

In [ ]:
X_train_prediction=classifier.predict(X_train)
y_true=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on training dataset:',y_true)

Accuracy on training dataset: 0.9504447268106735


Accuracy on test data

In [ ]:
X_test_prediction=classifier.predict(X_test)
y_pred=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on test dataset:',y_pred)

Accuracy on test dataset: 0.9137055837563451


Creating the Confusion matrix  

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(X_test_prediction, Y_test) 
cm 

array([[93, 11],
       [ 6, 87]])

**SVM Model**

In [ ]:
classifier1 = SVC(kernel='linear', random_state=2)
classifier1.fit(X_train, Y_train)  

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=2, shrinking=True, tol=0.001,
    verbose=False)

**Model Evaluation**

Accuracy on training data

In [ ]:
X_train_prediction=classifier1.predict(X_train)
y_true=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on training dataset:',y_true)


Accuracy on training dataset: 0.9021601016518425


Accuracy on test data

In [ ]:
X_test_prediction=classifier1.predict(X_test)
y_pred=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on test dataset:',y_pred)

Accuracy on test dataset: 0.8781725888324873


Creating the Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(X_test_prediction, Y_test)  
cm

array([[93, 18],
       [ 6, 80]])

**Random** **Forest** **Model**

In [ ]:
classifier2= RandomForestClassifier(n_estimators= 20, criterion="entropy",random_state=2)  
classifier2.fit(X_train, Y_train)  

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=2, verbose=0,
                       warm_start=False)

**Model Evaluation**

Accuracy on training data

In [ ]:
X_train_prediction=classifier2.predict(X_train)
y_true=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on training dataset:',y_true)

Accuracy on training dataset: 0.9987293519695044


Accuracy on test data

In [ ]:
X_test_prediction=classifier2.predict(X_test)
y_pred=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on test dataset:',y_pred)

Accuracy on test dataset: 0.9137055837563451


Creating the Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(X_test_prediction, Y_test)  
cm

array([[95, 13],
       [ 4, 85]])

So, from the Accuracy socre we can see there is small difference in percentage of training set and test set, it means our model has performed really well. If there is large difference between training and test set accuracy then we can say the either Overfitting or Underfitting has happened. Hence, after going through the results of all the three model we can say that Random Forest Model has performed better than SVM and Logistic Regression for our dataset. We can also apply other models like KNN, Naive Bayes Algorithm, Decision tree Algorithms to our dataset.